name: CI/CD Pipeline

on:
  push:
    branches: [ lab-6 ]
  pull_request:
    branches: [ lab-6 ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  all-tests: # Назовем общим именем
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x] # Оставим одну версию для экономии времени

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Unit Tests (Jest)
      run: npm run test:unit
      continue-on-error: true # Чтобы отчет все равно собрался, если тест упал

    - name: Run BDD Tests (Cucumber)
      run: npm run test:bdd
      continue-on-error: true

    - name: Run UI Tests (Playwright)
      run: |
        npm start &
        npm run test:ui
      continue-on-error: true

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.os }}
        path: allure-results/

  publish-report:
    runs-on: ubuntu-latest
    needs: all-tests
    if: always()
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Results
      uses: actions/download-artifact@v4
      with:
        path: allure-results-all
        merge-multiple: true

    - name: Allure Report Action
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: allure-results-all
        gh_pages: gh-pages
        allure_report: allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
    
    - name: send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🚀 Все уровни тестов завершены!
          Jest (Unit) ✅
          Cucumber (BDD) ✅
          Playwright (UI) ✅
          Отчет: https://pain-killeror.github.io/ATBP_lab1_parking/